### ISSUE TITLE
.NET Core Roadmap for .NET 8

### ISSUE THREAD

**Issue by rizwan3d** [rizwan3d/SharpRISCV#8]
- [x] Update Target Framework - https://github.com/rizwan3d/SharpRISCV/commit/2e386a96019ee301402bf90f944550bd2efed900
- [x] [Primary constructors](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors) - https://github.com/rizwan3d/SharpRISCV/commit/d1b1544e6da3e67a92d7053be6578e2e5eca7623
- [x] [Collection expressions](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/collection-expressions) - https://github.com/rizwan3d/SharpRISCV/commit/48ac291177ee7daf0d922640e29c59163aeec068
- [x] [Target-typed new](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/new-operator) - https://github.com/rizwan3d/SharpRISCV/commit/a2eae3d1e546bad27d10fa1882de929e36f140ba

**Comment by rizwan3d** [comment]
Completed
